[package]
name = "deepviewrt-sys"
description = "Low-level FFI bindings for deepview-rt Library"
readme = "README.md"
license-file = "LICENSE.txt"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "^0.2"
